services:
  backend:
    image: ghcr.io/baeshoon/tasks-backend:latest
    pull_policy: always
    container_name: tasks-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasks
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s
    networks:
      - tasks-network

  db:
    image: postgres:latest
    container_name: tasks-db
    restart: always
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge

volumes:
  postgres-data:
