services:
  backend:
    image: openjdk:17
    container_name: tasks-backend
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasks
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - tasks-network

  db:
    image: postgres:latest
    container_name: tasks-db
    restart: always
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tasks-network

  frontend:
    image: node:22
    container_name: tasks-frontend
    working_dir: /app
    volumes:
      - ./task-frontend:/app
    command: >
      sh -c "pnpm install && pnpm build && pnpm start"
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge

volumes:
  postgres-data:
