services:
  backend:
    image: openjdk:17
    container_name: tasks-backend
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasks
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - tasks-network

  db:
    image: postgres:latest
    container_name: tasks-db
    restart: always
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge

volumes:
  postgres-data:
