name: Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      # - name: Get pnpm store directory
      #   id: pnpm-cache
      #   run: |
      #     echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      # - name: Setup pnpm cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-store-

      # - name: Cache Cypress binary
      #   uses: actions/cache@v3
      #   id: cypress-cache
      #   with:
      #     path: ~/.cache/Cypress
      #     key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-cypress-

      - name: Start containers
        run: docker compose up -d

      - name: Install dependencies
        run: pnpm install

      - name: Install Dependency
        run: apt-get install libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb

      - name: Verify and install Cypress if needed
        run: |
          pnpx cypress verify || pnpx cypress install

      - name: Cypress run
        uses: cypress-io/github-action@master
        with:
          build: pnpm build
          start: pnpm dev
          wait-on: "http://localhost:5173"
          browser: chrome
          command: pnpm test
          install: false
